<font size=6 color="#0098CD">
Trabajo: Eliminación gaussiana
</font>

---

**Asignatura:** Álgebra Lineal

**Presentado por:** *Ronaldo Jimenéz Acosta*

**Fecha:** 9 - Nov - 2022

--- 

### 1. Objetivos
* Aplicar  los  conceptos  abordados  en  los  temas  1  y  2,  específicamente,  aquellos 
relacionados con solución de sistemas de ecuaciones lineales.

* Utilizar el lenguaje de programación Python para realizar cálculos básicos, 
representaciones gráficas en 3D y operaciones con matrices.

### 2. Descripción de la actividad y pautas de elaboración
A continuación, se plantean tres sistemas de ecuaciones lineales que deben 
resolverse aplicando los conceptos y procedimientos abordados en los temas 1 y 2. 
La entrega debe hacerse únicamente en formato PDF. Extensión máxima: 10 páginas.

#### Sistema de ecuaciones 1 $\color{green}{\text{(3 puntos)}}$

>$2x - y + 3z = 16$
>
>$4x + 0y - 2z = -4$
>
>$x + 3y - z = -9$


a) Traza  las  gráficas  de  las  tres  ecuaciones  en  el  mismo  sistema  de  coordenadas 
cartesianas.  ¿Qué  se  puede  afirmar  sobre  la  solución  del  sistema?  Explica  tu 
respuesta.

> **R/=** En el punto $(1, -2,  4)$ X, Y, Z, respectivamente es el punto de cruce de las 3 ecuaciones, por lo tanto es la solución al sistema.

In [ ]:
from IPython.display import IFrame

IFrame(src="https://www.geogebra.org/3d?lang=es",
       width=1080, height=600)

![img_grafica_1](https://user-images.githubusercontent.com/53100460/199523967-06e506f1-38ce-4de3-8bbc-5df8dc5d7d6d.png)

b) Resuelve  el  sistema  aplicando  el  método  de  Gauss.  Registra  el  procedimiento 
paso a paso y la solución.

In [29]:
import numpy as np
print('# 1. expresar el sistema de ecuaciones lineales como una matriz aumentada')
A = np.array([[2,-1,3,16],[4,0,-2,-4],[1,3,-1,-9]])
print(A)
print()

print('# 2. intercambiamos la fila 3 por la fila 1 (F3 <--> F1)')
A = np.array([[1,3,-1,-9],[4,0,-2,-4],[2,-1,3,16]])
print(A)
print()

print('# 3. para obtener el primer 0 hacemos: F2 - 4F1')
F2 = A[1] - 4*A[0]
print(F2)
print('simplicamos')
F2_s = F2/2
print(F2_s)
print()

print('#. primer 0 conseguido')
A[1] = F2_s
print(A)
print()

print('# 3. para obtener el segundo 0 hacemos: F3 - 2F1')
F3 = A[2] - 2*A[0]
print(F3)
print()

print('#. segundo 0 conseguido')
A[2] = F3
print(A)
print()

print('# 3. para obtener el tercer 0 hacemos: 6F3 - 7F2')
F3_2 = 6*A[2] - 7*A[1]
print(F3_2)
print()

print('#. tercer 0 conseguido')
A[2] = F3_2
print(A)
print()

# 1. expresar el sistema de ecuaciones lineales como una matriz aumentada
[[ 2 -1  3 16]
 [ 4  0 -2 -4]
 [ 1  3 -1 -9]]

# 2. intercambiamos la fila 3 por la fila 1 (F3 <--> F1)
[[ 1  3 -1 -9]
 [ 4  0 -2 -4]
 [ 2 -1  3 16]]

# 3. para obtener el primer 0 hacemos: F2 - 4F1
[  0 -12   2  32]
simplicamos
[ 0. -6.  1. 16.]

#. primer 0 conseguido
[[ 1  3 -1 -9]
 [ 0 -6  1 16]
 [ 2 -1  3 16]]

# 3. para obtener el segundo 0 hacemos: F3 - 2F1
[ 0 -7  5 34]

#. segundo 0 conseguido
[[ 1  3 -1 -9]
 [ 0 -6  1 16]
 [ 0 -7  5 34]]

# 3. para obtener el tercer 0 hacemos: 6F3 - 7F2
[ 0  0 23 92]

#. tercer 0 conseguido
[[ 1  3 -1 -9]
 [ 0 -6  1 16]
 [ 0  0 23 92]]




c) Obtén  la  solución  del  sistema  usando  **numpy.linalg.solve**.  Compara  esta 
solución con la obtenida en el literal b).

In [30]:
import numpy as np
# Matriz A
A = np.array([[2, -1, 3], [4, 0, -2], [1, 3, -1]])
# Vector b
b = np.array([16, -4, -9])
# Solución
x = np.linalg.solve(A, b)
print(x)
print('Comprobamos que A * x = b')
print(np.matmul(A, x))

[ 1. -2.  4.]
Comprobamos que A * x = b
[16. -4. -9.]


#### Solucion:

>$\begin{bmatrix}
 X &\\
 Y &\\
 Z 
\end{bmatrix}$
> $=$ 
> $\begin{bmatrix}
 1 &\\
 -2 &\\
 4 
\end{bmatrix}$