<font size=6 color="#0098CD">
Álgebra Lineal
</font>
<p></p>
<font size=6>
Cuaderno de ejercicios - Tema 1A
</font>


# 1. Conceptos básicos

## 1.1. Definición
Una **matriz** es un **arreglo rectangular** de elementos dispuestos en **filas** y **columnas**. Las matrices se representan con letras **mayúsculas**, normalmente las primeras del abecedario, y en negrita. Por ejemplo:

>$ A = \begin{bmatrix}
1  & 0 & 2 & -3\\
-1 & 4 & 2 & 7
\end{bmatrix}$

Utilizaremos la librería **NumPy** de Python para trabajar con matrices. Inicialmente importamos la librería y luego creamos la matriz:

```python
import numpy as np
A = np.array([[1, 0, 2, -3], [-1, 4, 2, 7]])
```

In [4]:
import numpy as np
A = np.array([[1, 0, 2, -3], [-1, 4, 2, 7]])
print(A)

[[ 1  0  2 -3]
 [-1  4  2  7]]


---
**Ejercicio**
>Crea la siguiente matriz:
>
>$ B = \begin{bmatrix}
 0 & -4 \\
 1 &  2 \\
 7 &  1
\end{bmatrix}$
---

In [3]:

B = np.array([[0, -4], [1,2], [7, 1]])
print(B)

[[ 0 -4]
 [ 1  2]
 [ 7  1]]


## 1.2. Orden de una matriz
Decimos que una matriz es $m \times n$ o de orden $m \times n$ si tiene **$m$ filas** y **$n$ columnas**. 

>La matriz $A$ anterior es $2 \times 4$; mientras que la matriz $B$ es $3 \times 2$

Obtengamos el orden de la siguiente matriz $C$:

```python
C = np.array([[3, 0, 5, -3, 0], [-1, 2, 2, 7, -1]])
print(C.shape)
```

---

**Ejercicio**
>Una matriz es **cuadrada** si tiene el mismo número de filas que de columnas. Crea la siguiente matriz y verifica que es $2 \times 2$: 
>
>$ D = \begin{bmatrix}
 -0.7 & 0.2 \\
 0.19 &  1.1 
\end{bmatrix}$
---

Para hacer referencia a un elemento de una matriz, usamos el número de la fila y de la columna. Por ejemplo:

>Sea $A$ la siguiente matriz $3 \times 3$:
>
>$ A = \begin{bmatrix}
 6 & -4 & 8 \\
 1 &  2 & 3 \\
 7 &  1 & 5
\end{bmatrix}$
>
>El elemento $(2, 3)$ de $A$ es $3$. También podemos decir que $a_{23}=3$.

**En Python se indexa desde cero**. Por lo tanto, si queremos recuperar el elemento $(2, 3)$ de la matriz $A$, procedemos como sigue:

```python
A = np.array([[6, -4, 8], [1, 2, 3], [7, 1, 5]])
print(A[1, 2])
```

---

**Ejercicio**
>a). Crea una matriz $B$ de orden $3 \times 3$.
>
>b). Comprueba el orden de la matriz.
>
>c). Lee el elemento $b_{13}$
>
>d). Reemplaza el elemento $b_{22}$ por $-1.25$
>
>e). Intercambia los elementos $(1, 1)$ y $(3, 3)$
>
>f). ¿Qué resultado se obtiene con cada una de las siguientes instrucciones?
>
> * print(B[1])
> * print(B[:,1])
> * print(B[:2])
> * print(B[:,:2])
---

En general, se expresa: $A = [a_{ij}]$; es decir, $A$ es la matriz cuyo elemento en la posición $(i, j)$ es $a_{ij}$.

## 1.3. Igualdad de matrices
Dos matrices son **iguales** si cumplen las siguientes condiciones:

a). Son del mismo orden.

b). Los elementos en cada posición son iguales (dos a dos).
>¿Las matrices $A$ y $B$ son iguales?
>
>$ A = \begin{bmatrix}
 2  & 3 \\
 -1 & 4 
\end{bmatrix}$
>
>$ B = \begin{bmatrix}
 2  & -3 \\
 1 & 4 
\end{bmatrix}$

En Python:
```python
A = np.array([[2, 3], [-1, 4]])
B = np.array([[2, -3], [1, 4]])
C = A == B
print(C.all())
```

# 2. Operaciones fundamentales

## 2.1. Suma
**Practica...**
>Escribe en esta celda la definición de suma de matrices

---
**Ejercicio**
>Dadas las siguiente matrices $A$ y $B$, obtén $C = A + B$ en Python. Explica el resultado. 
>
>$ A = \begin{bmatrix}
 2  & 3 & 4 \\
 -1 & 4 & 0
\end{bmatrix}$
>
>$ B = \begin{bmatrix}
 2  & -3 \\
 1  &  4 \\
 0  &  5
\end{bmatrix}$
---

---
**Ejercicio**
>Dadas las siguiente matrices $A$ y $B$, obtén $C = A - B$, primero en forma manual y luego en Python.
>
>$ A = \begin{bmatrix}
 2  & 3 & 4 \\
 -1 & 4 & 0
\end{bmatrix}$
>
>$ B = \begin{bmatrix}
 2   & -3 & -4 \\
 -1  &  4 & 2
\end{bmatrix}$
---

## 2.2. Producto

### 2.2.1. Producto por un escalar
**Practica...**
>Escribe en esta celda la definición de producto de un escalar por una matriz

---
**Ejercicio**
>Dada la siguiente matriz $A$ calcula $B = \frac{1}{2} A$. Comprueba en forma manual algunos elementos de la matriz $B$. 
>
>$ A = \begin{bmatrix}
 20  & 13 & 7.25 \\
 -10 & 4 & 0
\end{bmatrix}$
>
---

### 2.2.2. Producto matricial
**Practica...**
>Escribe en esta celda la definición de producto de matrices

---
**Ejercicio**
>Dadas las siguiente matrices $A$ y $B$, obtén $C = AB$ en Python. Explica el resultado. 
>
>$ A = \begin{bmatrix}
 2  & 3 & 4 \\
 -1 & 4 & 0
\end{bmatrix}$
>
>$ B = \begin{bmatrix}
 2  & -3 & 3 \\
 1  &  4 & 0
\end{bmatrix}$
---

---
**Ejercicio**
>Dadas las siguiente matrices $A$ y $B$, obtén $C = AB$, primero en forma manual, luego en Python.
>
>$ A = \begin{bmatrix}
 2  & 3 & 4 \\
 -1 & 4 & 0
\end{bmatrix}$
>
>$ B = \begin{bmatrix}
 2  & -3 \\
 1  &  4 \\
 0  &  5
\end{bmatrix}$
---

# 3. Ejercicios complementarios

a). Explica la diferencia entre las siguientes instrucciones. Asume que $A$ y $B$ son matrices cuadradas de orden $n$:
>```python
print(A*B)
print(np.matmul(A, B))
```

b). ¿El producto de matrices es conmutativo? Es decir, ¿$AB = BA$? Explica tu respuesta.

c). Escribe un programa para la multiplicación de una matriz $A$ de orden $m \times p$ y una matriz $B$ de orden $p \times n$. 

d). Consulta diferentes algoritmos para la multiplicación de matrices e identifica el más eficiente.